name: my-app
registry_host: gcr.io
registry_user: commercial-tribe
tags:
  - latest
env:
  APP_SOURCE: "jetson"
  RAZ:
    config_map: "some.value"
  BAR:
    config_map:
      name: some-config-map
      key: some-key
  BAZ:
    secret: some-key

ingress:
  tls:
    acme: true

service: true

config_map:
  some.value: "goop"

volumes:
  /app:
    spec:
      name: "something"
      hostPath:
        path: /tmp/test
  /myVol:
    claim:
      size: hi
      storage_class: slow
      access_modes:
        - ReadWriteOnce
  /auth: 50Gi

secrets:
  apiKey: "1234"

healthcheck:
  readiness: true
  http:
    port: default
    path: /

# Set the ports: this will create the ports on the container and on the service
ports:
  http: 80 # will generate a env var of DEFAULT_PORT

clusters:
  staging:
    ingress:
      hosts:
        commercialtribe.ninja:
          tls:
            acme: true
          paths:
            - /
  production:
    ingress:
      hosts:
        commercialtribe.net:
          tls:
            acme: true
          paths:
            /auth: http
            /other: 8080
    config_map:
      some.value: "tada"
