name: my-app

# Specify where to push the docker image
registry_host: gcr.io
registry_user: commercial-tribe

# specify the tags that we need to set
tags:
  - latest

# Define config maps to be used in this app
config_map:
  some.value: "goop"

# Define secrets to be used in this app
secrets:
  apiKey: "1234"

# define the env variables exposed to the containers
env:
  # define an env var with an inline value
  APP_SOURCE: "jetson"

  # define an env var that references this templates config-map
  RAZ:
    config_map: "some.value"

  # define an env var that references a named config-map
  BAR:
    config_map:
      name: some-config-map
      key: some-key

      # define an env var that references this templates secrets
  BAZ:
    secret: some-key

  # define an env var that references a named secret
  TAZ:
    secret:
      name: super-secret
      key: name

# define global ingress settings
ingress:
  annotations:
    kubernetes.io/tls-acme: "true"

# Specify if this deployment is a service
service: true

# Volumes and their mount paths
volumes:
  /app:
    spec:
      name: "something"
      hostPath:
        path: /tmp/test
  /myVol:
    claim:
      size: 100Gi
      storage_class: slow
      access_modes:
        - ReadWriteOnce
  /auth: 50Gi

# Set the ports: this will create the ports on the container and on the service
ports:
  http: 80 # will generate a env var of DEFAULT_PORT

# Healthcheck
healthcheck:
  readiness: true
  http:
    port: default
    path: /

# Define deployment autoscaling
# autoscale:
#   min: 2
#   max: 5

# Cluster Specific Settings
clusters:
  staging:
    ingress:
      tls: true
      hosts:
        frontend.{{metadata.name}}.commercialtribe.ninja:
          paths:
            - /
  production:
    ingress:
      hosts:
        commercialtribe.net:
          paths:
            /auth: http
            /other: 8080
    config_map:
      some.value: "tada"
